Repository openshift/cluster-api-provider-aws, pull requests merged in 2018-10, with the labels that each got.

#64 hack/aws-provision.sh: make it runnable from any directory
  hack/aws-provision.sh
Labels: approved, lgtm, size/XS

#62 E2E: verify node roles and node machine matching
  Makefile
  examples/provider-components.yml
  test/framework/clusterapi.go
  test/framework/clusters.go
  test/framework/framework.go
  test/framework/machines.go
  test/machines/awsclient.go
  test/machines/machines_test.go
  test/uploadDockerImages.sh
  test/utils/manifests.go
Labels: approved, lgtm, size/XXL

#65 Terminate instances before destroying vpc
  hack/aws-provision.sh
  hack/prebuild/main.tf
Labels: approved, lgtm, size/S

#69 Add more owners
  OWNERS
Labels: approved, lgtm, size/XS

#68 tooling unification
  Makefile
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
Labels: approved, lgtm, size/M

#71 move cloud library into pkg
  Makefile
  cmd/aws-actuator/main.go
  cmd/cluster-controller/main.go
  cmd/machine-controller/main.go
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/actuators/machine/utils.go
  pkg/cloud/aws/client/client.go
  pkg/cloud/aws/client/fake/fake.go
  pkg/cloud/aws/client/mock/client_generated.go
  pkg/cloud/aws/controllers/cluster/controller.go
  pkg/cloud/aws/controllers/cluster/options/options.go
  pkg/cloud/aws/controllers/machine/controller.go
  pkg/cloud/aws/controllers/machine/options/options.go
  pkg/cloud/aws/logging/logging.go
  pkg/cloud/aws/providerconfig/doc.go
  pkg/cloud/aws/providerconfig/register.go
  pkg/cloud/aws/providerconfig/types.go
  pkg/cloud/aws/providerconfig/v1alpha1/doc.go
  pkg/cloud/aws/providerconfig/v1alpha1/register.go
  pkg/cloud/aws/providerconfig/v1alpha1/types.go
  pkg/cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/providerconfig/zz_generated.deepcopy.go
  test/integration/create_update_delete_test.go
  test/machines/awsclient.go
  test/machines/machines_test.go
  test/utils/manifests.go
Labels: approved, lgtm, size/M

#70 Makefile: add Go debug support for local binaries
  Makefile
Labels: approved, lgtm, size/S

#74 unify clusterid retrieval
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, lgtm, size/S

#79 Update Makefile
  Makefile
Labels: approved, lgtm, size/XS

#72 E2e assertions
  pkg/cloud/aws/actuators/machine/utils.go
  test/machines/awsclient.go
  test/machines/machines_test.go
Labels: approved, lgtm, size/M

#78 Drop duplicate instance tags, if exists
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/M

#84 update and run scale down patches
  0001-Delete-annotated-machines-first-when-scaling-down.patch
  0002-Sort-machines-before-syncing.patch
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/L

#82 Load Balancer update
  pkg/apis/awsproviderconfig/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/M

#83 Rename ClusterName to ClusterID
  pkg/apis/awsproviderconfig/v1alpha1/awsmachineproviderconfig_types.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  test/integration/create_update_delete_test.go
Labels: approved, lgtm, size/S

#92 Logrus to glog
  cmd/aws-actuator/main.go
  cmd/manager/main.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/actuators/machine/utils.go
  pkg/cloud/aws/logging/logging.go
  test/integration/create_update_delete_test.go
Labels: approved, lgtm, size/L

#91 add unit test for buildEC2Filters
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/M

#94 add json tags and tests for providerconfig and provider status
  Makefile
  pkg/apis/awsproviderconfig/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsproviderconfig/v1alpha1/awsmachineproviderconfig_types_test.go
  pkg/apis/awsproviderconfig/v1alpha1/register.go
  pkg/apis/awsproviderconfig/v1alpha1/register_test.go
  pkg/apis/awsproviderconfig/v1alpha1/v1alpha1_suite_test.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/actuators/machine/utils.go
  test/utils/manifests.go
Labels: approved, lgtm, size/L

#95 use proper fmt script
  Makefile
  hack/verify-gofmt.sh
Labels: approved, lgtm, size/M

#93 updateMachineStatus: Log changes with ObjectReflectDiff
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#88 Stop nonstop status reconciliation
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, lgtm, size/S
