Repository openshift/cluster-api-provider-aws, pull requests merged in 2018-12, with the labels that each got.

#117 rename test-e2e to unify this target meaning along all repos
  Makefile
Labels: approved, lgtm, size/XS

#118 Import right context package
  cmd/aws-actuator/main.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  test/integration/create_update_delete_test.go
Labels: approved, lgtm, size/XS

#109 Record machine events
  cmd/aws-actuator/main.go
  cmd/manager/main.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/M

#110 Revendor deps to deploy manager controller with machine controller
  Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/clusterapi.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machines.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
Labels: approved, lgtm, size/L

#111 Switch aws-actuator bootstrap to deploy CRD based machine API
  README.md
  cmd/aws-actuator/README.md
  cmd/aws-actuator/main.go
  cmd/aws-actuator/utils/utils.go
  config/controllers/deployment.yaml
  config/crds/awsproviderconfig_v1alpha1_awsmachineproviderconfig.yaml
  config/crds/cluster.crd.yaml
  config/crds/machine.crd.yaml
  config/crds/machinedeployment.crd.yaml
  config/crds/machineset.crd.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  config/samples/awsproviderconfig_v1alpha1_awsmachineproviderconfig.yaml
  examples/cluster-api-server.yaml
  examples/provider-components.yml
Labels: approved, lgtm, size/XXL

#113 e2e gating
  Makefile
  test/e2e/main.go
  test/e2e/provider_expectations.go
Labels: approved, lgtm, size/L

#114 Turn coding/decoding functions into codec methods
  pkg/apis/awsproviderconfig/v1alpha1/register.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/actuators/machine/utils.go
  pkg/cloud/aws/actuators/machine/utils_test.go
  test/machines/utils.go
Labels: approved, lgtm, size/M

#124 crd/machinesets: add additional printer columns
  config/crds/machineset.crd.yaml
Labels: approved, lgtm, size/S

#126 Remove user from owners
  OWNERS
Labels: approved, lgtm, size/XS

#122 Increase unit test coverage of pkg/cloud/aws/actuators/machine
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/actuators/machine/awsclient_test.go
  pkg/cloud/aws/actuators/machine/instaces_test.go
  pkg/cloud/aws/actuators/machine/loadbalancers_test.go
  pkg/cloud/aws/actuators/machine/stubs.go
  pkg/cloud/aws/actuators/machine/utils.go
Labels: approved, lgtm, size/XXL
