Repository openshift/cluster-api-provider-aws, pull requests merged in 2018-08, with the labels that each got.

#28 Lookup for AMI using filters
  cloud/aws/actuators/machine/actuator.go
  examples/machine-set.yaml
  examples/machine-with-user-data.yaml
  examples/machine.yaml
  examples/master-machine.yaml
  examples/worker-machine.yaml
Labels: approved, size/L

#21 Change apiVersion from awsproviderconfig to aws.cluster.k8s.io.
  cloud/aws/providerconfig/register.go
  cloud/aws/providerconfig/v1alpha1/register.go
  clusterctl/examples/aws/cluster.yaml.template
  examples/machine-set.yaml
  examples/machine-with-user-data.yaml
  examples/machine.yaml
  examples/master-machine.yaml
  examples/worker-machine.yaml
Labels: approved, lgtm

#31 Prefix machines when bootstrapping
  cmd/aws-actuator/main.go
Labels: approved, size/XS

#32 Set bridge-nf-call-iptables
  examples/master-user-data.sh
  examples/master-userdata.yaml
Labels: approved, size/M

#35 add support for filters on sg and subnet
  cloud/aws/actuators/machine/actuator.go
  examples/machine-with-filters.yaml
Labels: approved, lgtm, size/L
