Repository openshift/cluster-api-provider-aws, pull requests merged in 2018-09, with the labels that each got.

#36 add scripts for lintin on ci
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  hack/yaml-lint.sh
Labels: approved, lgtm, size/M

#37 fix lints path
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
Labels: approved, lgtm, size/S

#39 Lint YAML
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/utils.go
  cmd/aws-actuator/main.go
  examples/addons.yaml
  examples/machine-set.yaml
  examples/machine-with-filters.yaml
  examples/machine-with-user-data.yaml
  examples/machine.yaml
  examples/master-machine.yaml
  examples/provider-components.yml
  examples/worker-machine.yaml
Labels: approved, size/L

#38 Prep Dockerfile for building with ART tooling.
  Dockerfile
  cmd/machine-controller/Makefile
Labels: approved, lgtm, size/S

#40 use origin-release images for tooling
  Makefile
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
Labels: approved, lgtm, size/S

#41 Bundle controller manager into the AWS machine controller image.
  Dockerfile
  examples/provider-components.yml
Labels: approved, lgtm, size/XS

#43 Address make vet/fmt complaints
  Makefile
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
  cloud/aws/actuators/machine/utils.go
  cloud/aws/client/client.go
  cloud/aws/controllers/cluster/controller.go
  cloud/aws/controllers/cluster/options/options.go
  cloud/aws/controllers/machine/controller.go
  cloud/aws/controllers/machine/options/options.go
  cloud/aws/providerconfig/register.go
  cloud/aws/providerconfig/types.go
  cloud/aws/providerconfig/v1alpha1/register.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cmd/aws-actuator/main.go
  cmd/machine-controller/main.go
  test/integration/create_update_delete_test.go
  test/utils/utils.go
Labels: approved, lgtm, size/L

#44 automate prebuild setup for AWS
  .gitignore
  hack/aws-provision.sh
  hack/prebuild/README.md
  hack/prebuild/main.tf
  hack/prebuild/security_groups.tf
  hack/prebuild/variables.tf
Labels: approved, size/L

#45 tf cleanup
  hack/prebuild/main.tf
  hack/prebuild/variables.tf
Labels: approved, lgtm, size/M

#46 Provider terraform and update examples to use filters
  Makefile
  cloud/aws/actuators/machine/actuator.go
  cmd/aws-actuator/README.md
  cmd/aws-actuator/main.go
  examples/machine-with-user-data.yaml
  examples/master-machine.yaml
  examples/worker-machine.yaml
  hack/aws-provision.sh
  hack/prebuild/main.tf
  hack/prebuild/security_groups.tf
  hack/prebuild/variables.tf
  test/infra.tf
  test/variables.tf
Labels: approved, lgtm, size/L

#48 Fix kubelet version to 1.11.3
  cmd/aws-actuator/main.go
  examples/master-user-data.sh
  examples/master-userdata.yaml
  examples/worker-user-data.sh
  examples/worker-userdata.yaml
  hack/prebuild/main.tf
Labels: approved, lgtm, size/M

#50 Clean Makefile
  Makefile
Labels: approved, lgtm, size/M

#49 Bootstrap cluster API stack
  cloud/aws/actuators/machine/actuator.go
  cmd/aws-actuator/README.md
  cmd/aws-actuator/main.go
  examples/provider-components.yml
Labels: approved, lgtm, size/L

#51 Run kubectl with explicit kubeconfig
  cmd/aws-actuator/main.go
Labels: approved, lgtm, size/XS

#52 Deploy worker machines via machineset
  cmd/aws-actuator/README.md
  cmd/aws-actuator/main.go
  examples/worker-machineset.yaml
Labels: approved, size/XL

#54 Annotate workers with node role
  examples/worker-machineset.yaml
Labels: approved, size/XS

#55 Propagate node role through machine spec label
  examples/worker-machineset.yaml
Labels: approved

#58 make golint more confident
  Makefile
Labels: approved, lgtm, size/XS

#61 Make golint happy
  cloud/aws/actuators/machine/actuator.go
  cmd/aws-actuator/main.go
Labels: approved, lgtm, size/S
