Repository openshift/cluster-api-provider-aws, pull requests merged in 2018-11, with the labels that each got.

#96 remove log-level option
  cmd/manager/main.go
  examples/provider-components.yml
Labels: approved, lgtm, size/S

#97 Incorporate availability zone into placement decision
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  test/machines/awsclient.go
  test/machines/machines_test.go
Labels: approved, lgtm, size/L

#102 make ineffectual assignment effective
  cmd/aws-actuator/main.go
Labels: approved, lgtm, size/M

#104 Machine status validation
  pkg/cloud/aws/actuators/machine/utils.go
  test/machines/machines_test.go
  test/machines/utils.go
Labels: approved, lgtm, size/L

#103 Add support for AWS Network Load Balancers
  Makefile
  hack/go-lint.sh
  pkg/apis/awsproviderconfig/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/client/client.go
  pkg/cloud/aws/client/fake/fake.go
  pkg/cloud/aws/client/mock/client_generated.go
Labels: approved, lgtm, size/L
