Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-02, with the labels that each got.

#148 Revendor actuator pkg
  0001-Delete-annotated-machines-first-when-scaling-down.patch
  0001-Upstream-677-Init-klog-in-manager-properly.patch
  0001-Validate-machineset-before-reconciliation.patch
  0002-Sort-machines-before-syncing.patch
  Gopkg.lock
  Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/clusters.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machines.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
Labels: approved, lgtm, size/L

#137 Add e2e tests for EBS support
  pkg/actuators/machine/awsclient.go
  pkg/actuators/machine/utils.go
  pkg/client/client.go
  pkg/client/fake/fake.go
  pkg/client/mock/client_generated.go
  test/machines/machines_test.go
  test/utils/manifests.go
Labels: approved, lgtm, size/L

#151 Update e2e test to run against machine.openshift.io
  test/e2e/main.go
  test/e2e/provider_expectations.go
Labels: approved, lgtm, size/M

#149 Bring back logic which is required for deep-copy auto-generation.
  hack/boilerplate/boilerplate.go.txt
  pkg/apis/addtoscheme_awsprovider_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/awsproviderconfig/group.go
  pkg/apis/awsproviderconfig/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#154 Update namespace -> openshift-machine-api
  test/e2e/main.go
Labels: approved, lgtm, size/XS

#158 Drain nodes by default unless explicitly set to exclude
  Makefile
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/stubs.go
  test/e2e/provider_expectations.go
  test/machines/machines_test.go
Labels: approved, lgtm, size/M

#162 Add more RBAC rules to properly drain
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
Labels: approved, lgtm, size/M

#163 Drop cluster test since it's not relevant for the actuator
  test/e2e/main.go
  test/e2e/provider_expectations.go
Labels: approved, lgtm, size/S

#159 New test for node draining (respecting PDB)
  pkg/actuators/machine/actuator.go
  test/e2e/main.go
  test/e2e/provider_expectations.go
Labels: approved, lgtm, size/L

#165 Allow to delete machine not linked to any node
  pkg/actuators/machine/actuator.go
Labels: approved, lgtm, size/S

#161 Rename labels from sigs.k8s.io to machine.openshift.io
  examples/machine-set.yaml
  examples/machine-with-filters.yaml
  examples/machine-with-user-data.yaml
  examples/machine.yaml
  examples/master-machine.yaml
  examples/worker-machine.yaml
  examples/worker-machineset.yaml
  pkg/actuators/machine/actuator.go
  pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
  test/e2e/provider_expectations.go
Labels: approved, lgtm, size/M

#164 Rename AWS credentials secret data keys
  pkg/client/client.go
Labels: approved, lgtm, size/XS

#167 client: add cluster-api-provider-aws to UserAgent for AWS API calls
  pkg/client/client.go
Labels: approved, lgtm, size/S

#155 Drop the yaml unmarshalling
  pkg/apis/awsproviderconfig/v1beta1/register.go
Labels: approved, lgtm, size/S

#169 deps: switch cluster-api dependency to use master branch
  Gopkg.toml
Labels: approved, lgtm, size/XS

#171 Update list of owners
  OWNERS
Labels: approved, lgtm, size/XS
