Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-12, with the labels that each got.

#277 Bug 1779107: Update Machine status with all instance IP addresses
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/utils.go
  pkg/actuators/machine/utils_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#278 [release-4.3] Bug 1780590: Update Machine status with all instance IP addresses
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/utils.go
  pkg/actuators/machine/utils_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#280 Bug 1781339: Ensure Spec.ProviderID is not empty string
  pkg/actuators/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#282 Include IPv6 addresses in Machine status
  pkg/actuators/machine/utils.go
  pkg/actuators/machine/utils_test.go
Labels: approved, lgtm, size/M

#284 Update owners
  OWNERS
Labels: approved, lgtm, size/XS

#279 [release-4.2] Bug 1781160: Update Machine status with all instance IP addresses
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/utils.go
  pkg/actuators/machine/utils_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L
