Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-06, with the labels that each got.

#220 Check if placement is not nil before accessing AvailabilityZone field
  pkg/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#218 Stopped instances existing
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/utils.go
Labels: approved, lgtm, size/M

#217 Consider non-terminated instances to be existing
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/utils.go
Labels: size/S

#227 Describe how to deploy machine API with AWS machine controller over kubernetes
  README.md
  config/bootstrap.sh
  config/controllers/deployment.yaml
  config/crds/cluster.crd.yaml
  config/crds/machine.openshift.io.crd.yaml
  config/crds/machinedeployment.openshift.io.crd.yaml
  config/crds/machineset.openshift.io.crd.yaml
  config/generate-bootstrap.sh
  config/kustomization.yaml
  config/master-machine.yaml
  config/master-user-data-secret.yaml
  config/master-user-data.sh
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  config/worker-machineset.yaml
  examples/addons.yaml
  examples/render-aws-secrets.sh
Labels: approved, lgtm, size/XL

#228 Drop aws-actuator bootstrap in favor of creating a machine with bootstrap user data
  cmd/aws-actuator/README.md
  cmd/aws-actuator/main.go
  cmd/aws-actuator/utils.go
  config/bootstrap.sh
  examples/cluster.yaml
  examples/machine-set.yaml
  examples/machine-with-filters.yaml
  examples/machine-with-user-data.yaml
  examples/machine.yaml
  examples/worker-machine.yaml
  examples/worker-user-data.sh
  examples/worker-userdata.yaml
Labels: approved, lgtm, size/XL

#229 Switch build to go 1.12
  Dockerfile
  Dockerfile.rhel7
  Makefile
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  pkg/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/S

#230 Prepend machine.Name to all logging
  pkg/actuators/machine/actuator.go
Labels: approved, lgtm, size/L
