Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-07, with the labels that each got.

#233 Revendor cluster api
  Gopkg.lock
  Makefile
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.toml
  vendor/github.com/openshift/cluster-api/pkg/controller/add_node.go
Labels: approved, lgtm, size/M

#237 Update vendor cluster-api and kubernetes-drain
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, lgtm, size/S

#238 Bug 1729243: Update vendor kubernetes-drain
  Gopkg.lock
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS
