Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-11, with the labels that each got.

#269 bug 1772163: Stop retieving instances by state tag filter on API call
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/stubs.go
  pkg/actuators/machine/utils.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#267 pkg/actuators/machine/utils: Drop running/pending comment from getInstances
  pkg/actuators/machine/utils.go
Labels: approved, lgtm, size/XS

#268 pkg/actuators/machine/utils: Client-side state filtering in getInstanceByID and getInstances
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/awsclient_test.go
  pkg/actuators/machine/instances_test.go
  pkg/actuators/machine/stubs.go
  pkg/actuators/machine/utils.go
  pkg/client/fake/fake.go
Labels: approved, lgtm, size/L

#270 Use getMachineInstances to find instances during update() call
  pkg/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#272 pkg/actuators/machine/actuator: Drop setMachineCloudProviderSpecifics comment
  pkg/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#271 Bug 1761882: pkg/actuators/machine/actuator: Eventual-consistency wait for machines
  pkg/actuators/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#273 Bug 1761882: pkg/actuators/machine: Eventual-consistency guards for Exists/Describe
  pkg/actuators/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
