Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-05, with the labels that each got.

#208 Update README.md
  Gopkg.lock
  README.md
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/hack/ci-integration.sh
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/infra.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
Labels: approved, lgtm, size/M

#209 Reduce machine controller watched scope to namespace
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/authorization/v1/generated.proto
  vendor/github.com/openshift/api/authorization/v1/types.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/hack/update-protobuf.sh
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/cluster-api/README.md
  vendor/github.com/openshift/cluster-api/cmd/manager/main.go
Labels: approved, lgtm, size/XL

#213 Sync with openshift cluster-api 0.1.0 rebase
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/cluster-api/CONTRIBUTING.md
  vendor/github.com/openshift/cluster-api/Dockerfile
  vendor/github.com/openshift/cluster-api/Makefile
  vendor/github.com/openshift/cluster-api/cmd/clusterctl/README.md
  vendor/github.com/openshift/cluster-api/config/crds/cluster_v1alpha1_machine.yaml
  vendor/github.com/openshift/cluster-api/config/crds/cluster_v1alpha1_machinedeployment.yaml
  vendor/github.com/openshift/cluster-api/config/crds/cluster_v1alpha1_machineset.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machine.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machinedeployment.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machineset.yaml
  vendor/github.com/openshift/cluster-api/config/default/manager_image_patch.yaml
  vendor/github.com/openshift/cluster-api/config/rbac/rbac_role.yaml
  vendor/github.com/openshift/cluster-api/docs/book/SUMMARY.md
  vendor/github.com/openshift/cluster-api/docs/book/common_code/cluster_controller.md
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_cluster_reconciliation.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_cluster_reconciliation.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_machine_controller_reconciliation.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_machine_controller_reconciliation.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_machine_deletion_block.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_machine_deletion_block.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_machinedeployment_reconciliation.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_machinedeployment_reconciliation.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_machineset_reconciliation.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_machineset_reconciliation.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_node_reconciliation.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/activity_node_reconciliation.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/sequence_cluster_creation.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/sequence_cluster_creation.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/sequence_cluster_deletion.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/sequence_cluster_deletion.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/sequence_machine_creation.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/sequence_machine_creation.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/sequence_machine_deletion.drawio
  vendor/github.com/openshift/cluster-api/docs/book/common_code/images/sequence_machine_deletion.svg
  vendor/github.com/openshift/cluster-api/docs/book/common_code/machine_controller.md
  vendor/github.com/openshift/cluster-api/docs/book/common_code/machinedeployment_controller.md
  vendor/github.com/openshift/cluster-api/docs/book/common_code/machineset_controller.md
  vendor/github.com/openshift/cluster-api/docs/book/common_code/node_controller.md
  vendor/github.com/openshift/cluster-api/docs/book/provider_implementations/register_schemes.md
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/delete_policy.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/status.go
Labels: approved, lgtm, size/XL

#210 Update machine.Spec.ProviderID field
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/stubs.go
Labels: approved, lgtm, size/M

#219 Fix CI/jenkins e2e env setup
  hack/prebuild/main.tf
Labels: approved, lgtm, size/XS
