Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-03, with the labels that each got.

#173 Delete node after removing cloud instance on deletion
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
Labels: approved, lgtm, size/S

#174 Move node draining from actuator into machine controller
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/stubs.go
  test/machines/machines_test.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
Labels: approved, lgtm, size/L

#172 Consistent log messages
  .gitignore
  cmd/aws-actuator/main.go
  cmd/manager/main.go
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/loadbalancers.go
  pkg/actuators/machine/utils.go
Labels: approved, lgtm, size/M

#176 Record update events as well
  pkg/actuators/machine/actuator.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/common/consts.go
  vendor/github.com/openshift/cluster-api/pkg/errors/machines.go
Labels: approved, lgtm, size/S

#180 Reduce resync period from 10 hours to 10 minutes
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#183 Do not be explicit about iops constraints
  pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
Labels: approved, lgtm, size/XS

#186 verify staleness of vendored cluster-api-actuator-pkg
  Makefile
  hack/verify-actuator-pkg.sh
Labels: approved, lgtm, size/S

#182 Drop unused labels from installer machineSets
  examples/machine-set.yaml
  examples/machine-with-filters.yaml
  examples/machine-with-user-data.yaml
  examples/machine.yaml
  examples/master-machine.yaml
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/stubs.go
  pkg/actuators/machine/utils.go
  pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
Labels: approved, lgtm, size/M
