Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-10, with the labels that each got.

#261 Error reporting
  go.mod
  go.sum
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/instances.go
  pkg/client/client.go
  vendor/github.com/openshift/cluster-api/cmd/manager/BUILD.bazel
  vendor/github.com/openshift/cluster-api/cmd/manager/main.go
  vendor/github.com/openshift/cluster-api/pkg/apis/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/common/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/defaults.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machineclass_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/common/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/error/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/noderefutil/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/drain/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/drain/drain.go
  vendor/github.com/openshift/cluster-api/pkg/errors/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/errors/clusters.go
  vendor/github.com/openshift/cluster-api/pkg/errors/deployer.go
  vendor/github.com/openshift/cluster-api/pkg/util/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/util/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#265 Add unit test coverage for actuator.create
  pkg/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/L

#266 Bug 1761882: Search for existing instances by instance ID
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/instances_test.go
  pkg/actuators/machine/utils.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
