Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-08, with the labels that each got.

#245 Bug 1734193: Wire provider spec EBS volume Encrypted field into ec2.EbsBlockDevice.Encrypted field
  pkg/actuators/machine/instances.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#246 Bump openshift/cluster-api dependencies
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machine.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machineset.yaml
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/sync.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/M

#248 Remove unused code
  test/integration/create_update_delete_test.go
Labels: approved, lgtm, size/L

#249 Do not access machine variable that is nil
  pkg/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#250 Update providerID field during update operation as well
  pkg/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#251 Bug 1733708: Bump cluster-api to include native drain lib with fixes
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/pkg/controller/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/drain/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/drain/drain.go
  vendor/github.com/openshift/kubernetes-drain/LICENSE
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#252 Add goimports into makefile
  Makefile
  hack/goimports.sh
  pkg/client/mock/client_generated.go
Labels: approved, lgtm, size/S

#256 bug 1744049: Vendor cluster-api to update InvalidConfigurationMachineError
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/M
