Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-01, with the labels that each got.

#128 Remove kubeclient in favor of runtime controller client
  cmd/aws-actuator/main.go
  cmd/aws-actuator/utils/utils.go
  cmd/manager/main.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/client/client.go
  test/integration/create_update_delete_test.go
  test/machines/machines_test.go
Labels: approved, lgtm, size/L

#136 Fix make test-e2e
  Makefile
Labels: approved, lgtm, size/XS

#132 EBS support
  pkg/actuators/machine/instaces_test.go
  pkg/actuators/machine/instances.go
  pkg/apis/awsproviderconfig/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsproviderconfig/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#135 [RFE] Drain nodes before deletion if requested
  Gopkg.lock
  cmd/manager/main.go
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  test/e2e/main.go
  test/e2e/provider_expectations.go
  vendor/github.com/go-log/log/LICENSE
  vendor/github.com/go-log/log/README.md
  vendor/github.com/go-log/log/capture/capture.go
  vendor/github.com/go-log/log/fmt/fmt.go
  vendor/github.com/go-log/log/info/info.go
  vendor/github.com/go-log/log/log.go
  vendor/github.com/go-log/log/log/log.go
  vendor/github.com/go-log/log/nest/nest.go
  vendor/github.com/go-log/log/print/print.go
  vendor/github.com/openshift/kubernetes-drain/LICENSE
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, lgtm, size/XXL

#138 Remove providerconfig
  cmd/aws-actuator/main.go
  config/crds/cluster.crd.yaml
  config/crds/machine.crd.yaml
  config/crds/machinedeployment.crd.yaml
  config/crds/machineset.crd.yaml
  examples/machine-set.yaml
  examples/machine-with-filters.yaml
  examples/machine-with-user-data.yaml
  examples/machine.yaml
  examples/master-machine.yaml
  examples/worker-machine.yaml
  examples/worker-machineset.yaml
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/stubs.go
  pkg/actuators/machine/utils.go
  pkg/actuators/machine/utils_test.go
  pkg/apis/awsproviderconfig/v1alpha1/register.go
  pkg/apis/awsproviderconfig/v1alpha1/register_test.go
  test/machines/machines_test.go
  test/utils/manifests.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#139 Update delete policy downstream patch and re-apply it
  0001-Delete-annotated-machines-first-when-scaling-down.patch
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/delete_policy.go
Labels: approved, lgtm, size/M

#140 Validate machineset before reconciling
  0001-Validate-machineset-before-reconciliation.patch
  Makefile
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/M

#142 Fix optional fields and omitempty
  pkg/apis/awsproviderconfig/v1alpha1/awsmachineproviderconfig_types.go
Labels: approved, lgtm, size/M

#141 Initialize klog alongside with glog
  0001-Upstream-677-Init-klog-in-manager-properly.patch
  Makefile
  cmd/manager/main.go
  vendor/sigs.k8s.io/cluster-api/cmd/manager/main.go
Labels: approved, lgtm, size/M

#143 Log if availability zone does not exist
  Makefile
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/instaces_test.go
  pkg/actuators/machine/instances.go
  pkg/client/client.go
  pkg/client/fake/fake.go
  pkg/client/mock/client_generated.go
Labels: approved, lgtm, size/M

#146 Apply tagList to the ebs volume
  pkg/actuators/machine/instances.go
Labels: approved, lgtm, size/XS

#145 Verify launchInstance failed/succeeded properly
  pkg/actuators/machine/instaces_test.go
Labels: approved, lgtm, size/M
