Repository openshift/cluster-api-provider-aws, pull requests merged in 2019-04, with the labels that each got.

#197 bump cluster-api-actuator-pkg
  Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/common.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machinehealthcheck.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machines.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/nodes.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/infra.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/utils.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/L

#193 Remove myself from OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#188 Skip deletion of stop machines if there is an error
  pkg/actuators/machine/actuator.go
Labels: approved, lgtm, size/S

#200 fix source paths when invoking vet and fmt scripts
  hack/go-fmt.sh
  hack/go-vet.sh
Labels: approved, lgtm, size/XS

#192 Remove clusterid tag
  pkg/actuators/machine/filter.go
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/utils.go
  test/machines/machines_test.go
Labels: approved, lgtm, size/M

#179 Version support
  Dockerfile
  Dockerfile.rhel7
  Gopkg.lock
  Makefile
  cmd/manager/main.go
  pkg/client/client.go
  pkg/version/version.go
  vendor/github.com/blang/semver/.gx/lastpubver
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/examples/main.go
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
Labels: approved, lgtm, size/XXL

#203 Sync with the latest openshift/cluster-api
  Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
Labels: approved, lgtm, size/M

#204 Sync with the latest cluster-api and cluster-api-actuator-pkg
  Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/hack/ci-integration.sh
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/L

#206 Revendor cluster api
  Gopkg.lock
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/utils.go
  pkg/actuators/machine/utils_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_cluster.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machine.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machinedeployment.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machineset.yaml
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/common_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
Labels: approved, lgtm, size/L

#207 Revendor drop machine.openshift.io cluster
  Gopkg.lock
  cmd/aws-actuator/main.go
  cmd/aws-actuator/utils.go
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/stubs.go
  test/integration/create_update_delete_test.go
  test/machines/machines_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/clusterapi.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/clusters.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/cluster_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/fake/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/fake/fake_cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/fake/fake_machine_client.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/generated_expansion.go
  vendor/github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/typed/machine/v1beta1/machine_client.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/generic.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/informers_generated/externalversions/machine/v1beta1/interface.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api/pkg/client/listers_generated/machine/v1beta1/expansion_generated.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/actuator.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/testactuator.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
  vendor/github.com/openshift/cluster-api/pkg/provider/example/actuators/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/provider/example/actuators/machine/machineactuator.go
Labels: approved, lgtm, size/XXL
