Repository openshift/cluster-api-provider-aws, pull requests merged in 2020-02, with the labels that each got.

#288 Bug 1796599: Save status before Patch()
  pkg/actuators/machine/actuator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#291 Bug 1798596: take into consideration all instance state for deletion
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/awsclient.go
  pkg/actuators/machine/awsclient_test.go
  pkg/actuators/machine/instances_test.go
  pkg/actuators/machine/utils.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#292 Bug 1798597: [release-4.3] take into consideration all instance states for deletion
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/awsclient.go
  pkg/actuators/machine/awsclient_test.go
  pkg/actuators/machine/instances_test.go
  pkg/actuators/machine/utils.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#294 Bug 1799034: [release-4.2] take into consideration all instance states for deletion
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/awsclient.go
  pkg/actuators/machine/awsclient_test.go
  pkg/actuators/machine/instaces_test.go
  pkg/actuators/machine/stubs.go
  pkg/actuators/machine/utils.go
  test/machines/machines_test.go
  test/machines/utils.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#295 Bug 1796595: [release-4.2] Mitigate aws eventual consistency issues
  go.mod
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/instances_test.go
  pkg/actuators/machine/stubs.go
  pkg/actuators/machine/utils.go
  pkg/client/client.go
  pkg/client/fake/fake.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/k8s.io/utils/pointer/OWNERS
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#290 Bug 1803766: Remove glog package in favor of klog
  cmd/manager/main.go
  go.mod
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/loadbalancers.go
  pkg/actuators/machine/utils.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL
