Repository openshift/cluster-api-provider-aws, pull requests merged in 2020-12, with the labels that each got.

#332 [OCPCLOUD-936] Bug 1902157: Mark node with condition when due for termination
  pkg/termination/handler.go
  pkg/termination/handler_test.go
  pkg/termination/termination_suite_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, lifecycle/stale

#372 support custom CA bundle for AWS API
  pkg/client/client.go
  pkg/client/client_test.go
Labels: approved, lgtm

#379 Bug 1907286: Ensure Machine is marked interruptible as well as Node
  pkg/actuators/machine/reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#380 Bug 1906740: Ensure the region is valid when creating AWS client
  cmd/manager/main.go
  pkg/client/client.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
