Repository openshift/cluster-api-provider-aws, pull requests merged in 2020-03, with the labels that each got.

#293 Add alexander-demichev and JoelSpeed to owners
  OWNERS
Labels: approved, lgtm, size/XS

#304 Remove bison from OWNERS file
  OWNERS
Labels: approved, lgtm

#302 Don't return error with invalid instance type in machineSet annotations reconciler.
  pkg/actuators/machineset/controller.go
Labels: approved, lgtm, size/S

#303 support KMS key for EBS encryption
  pkg/actuators/machine/instances.go
  pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
  pkg/apis/awsproviderconfig/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS

#305 Refactor conditions logic
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/utils.go
  pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
Labels: approved, lgtm

#307 Split provider status and config
  cmd/aws-actuator/utils.go
  cmd/manager/main.go
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/instances_test.go
  pkg/actuators/machine/stubs.go
  pkg/actuators/machine/utils.go
  pkg/actuators/machine/utils_test.go
  pkg/actuators/machineset/controller.go
  pkg/actuators/machineset/controller_test.go
  pkg/apis/addtoscheme_openshiftawsprovider_v1beta1.go
  pkg/apis/awsprovider/group.go
  pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go
  pkg/apis/awsprovider/v1beta1/awsproviderstatus_types.go
  pkg/apis/awsprovider/v1beta1/doc.go
  pkg/apis/awsprovider/v1beta1/register.go
  pkg/apis/awsprovider/v1beta1/register_test.go
  pkg/apis/awsprovider/v1beta1/zz_generated.deepcopy.go
  pkg/client/mock/client_generated.go
Labels: approved, lgtm

#306 [OCPCLOUD-801] Add support for Spot Instances in MachineProviderConfig
  go.mod
  go.sum
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/instances_test.go
  pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, lgtm

#308 [OCPCLOUD-802] Add Spot terminationion notice handler
  Dockerfile
  Dockerfile.rhel7
  Makefile
  cmd/termination-handler/main.go
  pkg/termination/handler.go
  pkg/termination/handler_test.go
  pkg/termination/termination_suite_test.go
Labels: approved, lgtm
