Repository openshift/cluster-api-provider-aws, pull requests merged in 2020-05, with the labels that each got.

#320 BUG 1831717: Ensure PublicIP is left out of JSON encoding if empty
  pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#318 Bug 1822200: Custom dns name support
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/machine_scope.go
  pkg/actuators/machine/machine_scope_test.go
  pkg/actuators/machine/reconciler_test.go
  pkg/actuators/machine/stubs.go
  pkg/actuators/machine/utils.go
  pkg/actuators/machine/utils_test.go
  pkg/client/client.go
  pkg/client/fake/fake.go
  pkg/client/mock/client_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#325 Bug 1840552: Update machine-api-operator dependency
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
