Repository openshift/cluster-api-provider-aws, pull requests merged in 2020-06, with the labels that each got.

#326 [release-4.4] Bug 1833359: Custom dns name support
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/stubs.go
  pkg/actuators/machine/utils.go
  pkg/actuators/machine/utils_test.go
  pkg/client/client.go
  pkg/client/fake/fake.go
  pkg/client/mock/client_generated.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#328 Add dgrigore to approvers
  OWNERS
Labels: approved, lgtm

#299 Add support for multiple block device mappings
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/instances_test.go
  pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go
Labels: approved, lgtm, release/4.6, size/L

#329 Add liveness/readiness probes
  cmd/manager/main.go
Labels: approved, lgtm
