Repository openshift/cluster-api-provider-aws, pull requests merged in 2020-09, with the labels that each got.

#349 Bug 1872080: Add Dockerfile.rhel to match build configuration in ocp-build-data
  Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#346 BUG 1866778: [aws] mapi_instance_create_failed doesn't work on aws
  go.mod
  go.sum
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/instances_test.go
  pkg/actuators/machine/reconciler.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/machine-api-operator/pkg/metrics/metrics.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#350 Bug 1875036: remove Dockerfile.rhel7
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#342 Bug 1864352: Add leader election mechanism to release 4.5
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#353 Bug 1878880: re-vendor machine-api-operator at e0db6b65
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#355 BUG 1875598: Ensure the Virtual Machine provider state is set to Unknown when Failed
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#356 Bug 1883497: Fix missing logs due to mixed klog versions
  cmd/manager/main.go
  cmd/termination-handler/main.go
  go.mod
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/loadbalancers.go
  pkg/actuators/machine/machine_scope.go
  pkg/actuators/machine/reconciler.go
  pkg/actuators/machine/utils.go
  pkg/apis/awsprovider/v1beta1/register.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
