Repository openshift/cluster-api-provider-aws, pull requests merged in 2020-07, with the labels that each got.

#315 [OCPCLOUD-492]; Run all machine api Controllers using leader election
  cmd/manager/main.go
Labels: approved, lgtm, release/4.6

#324 Enable metrics
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/actuators/machine/instances.go
  pkg/actuators/machine/reconciler.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/golang/mock/mockgen/mockgen.go
  vendor/github.com/golang/mock/mockgen/model/model.go
  vendor/github.com/golang/mock/mockgen/parse.go
  vendor/github.com/golang/mock/mockgen/reflect.go
  vendor/github.com/openshift/cluster-api-provider-gcp/LICENSE
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/doc.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/register.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/vsphereproviderconfig_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/vsphereproviderstatus_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/clientset.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/generated_expansion.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machine.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machine_client.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machineset.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/machine/v1beta1/interface.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/machine/v1beta1/machine.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/machine/v1beta1/machineset.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/listers/machine/v1beta1/expansion_generated.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/listers/machine/v1beta1/machine.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/listers/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/listers/machine/v1beta1/machineset.go
  vendor/github.com/openshift/machine-api-operator/pkg/metrics/metrics.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/LICENSE
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderstatus_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, release/4.6

#333 [release-4.4] Bug 1810531: Revendor MAO with timeout formatting fix
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#339 BUG 1858400: [Performance] Lease refresh period for machine-api-controllers is too high, causes heavy writes to etcd at idle
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#341 Bug 1857175: Revendor mao to bring https://github.com/openshift/machine-api-operator/pull/644
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#327 Add support for custom endpoints
  go.sum
  pkg/client/client.go
Labels: approved, lgtm

#337 Ensure we are testing scheme registration for termination handler
  pkg/termination/handler_test.go
  pkg/termination/termination_suite_test.go
Labels: approved, lgtm
