Repository openshift/cluster-api-provider-aws, pull requests merged in 2021-03, with the labels that each got.

#390 Bug 1934021: Ensure response body is closed when we are finished with the request
  pkg/termination/handler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#386 [OCPCLOUD-1066] Makefile fix
  Makefile
  README.md
  hack/go-fmt.sh
  hack/go-lint.sh
  hack/go-vet.sh
  hack/goimports.sh
  hack/imagebuilder.sh
  hack/owner_reset.sh
  hack/verify-actuator-pkg.sh
  pkg/actuators/machine/machine_scope_test.go
  pkg/actuators/machine/stubs.go
Labels: approved, lgtm

#392 Bug 1910318: Add condition to show actuator exists condition on machine
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/condition_consts.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/github.com/openshift/machine-api-operator/pkg/util/conditions/conditions.go
  vendor/github.com/openshift/machine-api-operator/pkg/util/conditions/getter.go
  vendor/github.com/openshift/machine-api-operator/pkg/util/conditions/matcher.go
  vendor/github.com/openshift/machine-api-operator/pkg/util/conditions/setter.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#393 Update EC2 instance types
  pkg/actuators/machineset/controller_test.go
  pkg/actuators/machineset/ec2_instance_types.go
Labels: approved, lgtm

#396 Bug 1910318: Ensure original conditions aren't mutated during reconcile
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#389 Bug 1880757: Unset target groups from LB on deletion
  pkg/actuators/machine/instances_test.go
  pkg/actuators/machine/loadbalancers.go
  pkg/actuators/machine/loadbalancers_test.go
  pkg/actuators/machine/reconciler.go
  pkg/actuators/machine/stubs.go
  pkg/client/client.go
  pkg/client/fake/fake.go
  pkg/client/mock/client_generated.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#397 Bug 1918910: Only log error on wrong instance type for scale from zero
  pkg/actuators/machineset/controller.go
  pkg/actuators/machineset/controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
