Repository openshift/cluster-api-provider-aws, pull requests merged in 2025-04, with the labels that each got.

#546 OCPBUGS-53727: bump to github.com/golang-jwt/jwt/v4@v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#545 ART-12521: update go mod dependency for konflux
  .gitignore
  vendor/github.com/sagikazarmark/locafero/.envrc
  vendor/github.com/sagikazarmark/slog-shim/.envrc
  vendor/github.com/spf13/viper/.envrc
  vendor/github.com/subosito/gotenv/.env
Labels: approved, lgtm, jira/valid-reference

#547 OCPBUGS-53726: Update golang-jwt to v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#548 OCPBUGS-54567: UPSTREAM: 5374: add marketType field validation
  api/v1beta2/awsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  exp/api/v1beta2/awsmachinepool_webhook.go
  exp/api/v1beta2/awsmachinepool_webhook_test.go
  openshift/infrastructure-components-openshift.yaml
  openshift/manifests/0000_30_cluster-api_04_cm.infrastructure-aws.yaml
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
